package example:calculator;

interface calculate {
    add-number: func(x: u32, y: u32) -> u32;
}

world calculator {
    export calculate;
    import example:adder/add;
}

world app {
    import calculate;
}
